/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/availability`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/profile`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/progress`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/notifications/client`; params?: Router.UnknownInputParams; } | { pathname: `/notifications/instructor`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/availability`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/progress`; params?: Router.UnknownOutputParams; } | { pathname: `/instructor/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications/client`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications/instructor`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/instructor/attendance${`?${string}` | `#${string}` | ''}` | `/instructor/availability${`?${string}` | `#${string}` | ''}` | `/instructor/dashboard${`?${string}` | `#${string}` | ''}` | `/instructor/profile${`?${string}` | `#${string}` | ''}` | `/instructor/progress${`?${string}` | `#${string}` | ''}` | `/instructor/schedule${`?${string}` | `#${string}` | ''}` | `/notifications/client${`?${string}` | `#${string}` | ''}` | `/notifications/instructor${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/availability`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/profile`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/progress`; params?: Router.UnknownInputParams; } | { pathname: `/instructor/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/notifications/client`; params?: Router.UnknownInputParams; } | { pathname: `/notifications/instructor`; params?: Router.UnknownInputParams; };
    }
  }
}
